### PR TITLE
Feat: Show bullet comments.

### PR DESCRIPTION
**Pull request by 34j**
#### What is it?
- [ ] Bugfix (user facing)
- [x] Feature (user facing)
- [ ] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR

- Show bullet comments.
- Change the visibility of bullet comments by pressing the button.

#### Before/After Screenshots/Screen Record

- Before:
- After:
image
image

#### Relies on the following changes

- InfinityLoop1309/NewPipeExtractor#19
Depends on `org.schabi.newpipe.extractor.bulletComments`.

#### APK testing 

The APK can be found by going to the "Checks" tab below the title. On the left pane, click on "CI", scroll down to "artifacts" and click "app" to download the zip file which contains the debug APK of this PR.

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by InfinityLoop1309** [comment]
AWESOME work! 
Thank you for implementing this long-waiting feature, which can benefit both BiliBili and NicoNico and bring them the origin user experience.
I am checking it.

**Comment by InfinityLoop1309** [comment]
Sorry but I can not find that button. Is there anything I need to do first?

**Comment by 34j** [comment]
I am sorry, but I have found four defects and would like to ask you to please hold off on the code review for both PRs. I should have checked a little more before opening PR.
- []Formatting the code
- []Custom View code should be decent.
- []Niconico comments are not displayed on some occasions though bullet comments are displayed.
- []Make the button to change visibility of comments appear only when necessary.

**Comment by InfinityLoop1309** [comment]
OK. You can mark it as draft now.

**Comment by InfinityLoop1309** [comment]
I got it and tried it. The bullet comments works well and smoothly :)
However, there are 2 points we need to discuss:
1. The bullet comment seems a little bit bigger on smartphones. I would like to make it smaller or have a preference to set the font size.
2. As the "NicoNico comments" are actually those bullet comments, I don't think it is a good idea to place it as the comments of the video. It looks strange, and is very different from the normal comments - those which are designed to be referenced and raise a discussion. I believe it should only appear in bullet comments, or alternatively in `live chat`(which is planned but not implemented yet)

**Comment by InfinityLoop1309** [comment]
I am planning to release a new version, as filters is a big enough feature for release. How is your planning about bullet comments? If you can finish it in about 1 week, I will wait to merge this feature. Alternatively, I can include this feature in next release.

Also, are you willing to help me maintain `AnimePipe`?  If yes, I can give you the `collaborator` permission, with which we can collaborate more easily.

**Comment by 34j** [comment]
As for the release, it may depend on the level of completeness required for this PR. Anyway I will leave it to you.
As for collaborator, I cannot responsibly say yes because I'm a moody person.

**Comment by InfinityLoop1309** [comment]
I am not a perfectionist. It works, so it has already satisfied the requirement. We just need to deal with the two points I mentioned before.

For collaborator, you can ask me to join when you want:)

**Comment by 34j** [comment]
Now comment size are adjusted compared to the mobile version of niconico. (Android has only one font family, so the display is slightly different from the web version of niconico.)
image

**Comment by InfinityLoop1309** [comment]
Seems good. Please let me know and mark the PR as "Ready for review" when you finished your work.

**Comment by 34j** [comment]
Patent Issues
Dwango has issued about 70 patents related to bullet comments, and I am concerned that my implementation may infringe on the patents. As far as I have researched, I have read that the patent is for "making the comments as non-overlapping as possible" and not for displaying the comments themselves. However, I am concerned because such an implementation in "wankome" has been removed. In addition, Dwango has removed many unofficial Nico Nico Douga applications and applications that display bulleted comments in the past.

Therefore, in order to absolutely prevent any possibility of infringement of the patent and to prove that I am not implementing the implementation "as a tool" for patent infringement, I would like you to change the implementation to one that animates the comments from bottom to top like YouTube livestream comments and request merging that as a whole. Is it OK?

**Comment by InfinityLoop1309** [comment]
I believe it is not an issue. It is almost impossible to develop free and open source softwares(FOSS) in full compliance with all the rules, as big techs have patented almost everything. Actually using apis from most services in a third-party app already violented their rules. 
In addition, we are FOSS and get no money from this project, so the worst condition is the repo get removed by Github(very unlikely). That case we can just migrate to other platform such as CodeBurg.

However, if the case is that you dont want because of moral reason, I will respect your decision. That case please show me in detail what is your alternative solution.

**Comment by 34j** [comment]
Violations of patent law are more serious than violations of terms of service, and bullet-pointed comments are not a moral issue. (I believe NewPipe or AnimePipe have not violated any terms of service.) In fact, Dwango filed a lawsuit against FC2 and demanded 100 million yen. In fact, Dwango recently filed a lawsuit against FC2 and demanded 100 million yen in damages. Also, as I mentioned above, Dwango has actually requested most of the apps to stop publishing based on patent infringement. (If they refuse to do so, the case could go to trial.)

I think the solution is for someone living in a country where Dwango does not have a patent (e.g. China, I think, but look it up) to write the code for bullet comments and also for someone living in a country where Dwango does not have a patent to publish and distribute AnimePipe. (In that case, they could even implement an algorithm to prevent bullet comments from overlapping.) In doing so, I need to ensure that the code I wrote does not provide "a tool for patent infringement".

Another solution is to wait about 5 years for the patent to expire. lol

**Comment by InfinityLoop1309** [comment]
If that is the case, may I just take your code and publish under my name? I believe they can do nothing with me XD

**Comment by InfinityLoop1309** [comment]
BiliBili also have the bullet-comment feature and I believe they never pay for the patent.

**Comment by 34j** [comment]
NO. Write your own code. The PRS were opened by mistake, I uploaded the code by mistake. So forget it. NEVER COPY THE CODE IN THE PRs. I will delete the branch later.

**Comment by InfinityLoop1309** [comment]
Fine.

**Comment by 34j** [comment]
@InfinityLoop1309
As I emailed to you, in order to prevent my code from being used as an instrument of patent infringement, I would like to ask you to try requesting the removal of two PRs in order to completely remove my `code` related to the patent from the Internet. Thank you in advance for your time. 
https://support.github.com/request/remove-data?tags=docs-generic
(This comment was written to inform github of my intentions, if it is needed.)

**Pull request closed without merging**
